#!/bin/sh

# close and remove old versions
palm-launch -c net.webpresso.froscon2010
palm-install -r net.webpresso.froscon2010

# package, install and run FrOSCon app on palm emulator
palm-package contents
palm-install net.webpresso.froscon2010_0.1.5_all.ipk
palm-launch net.webpresso.froscon2010
