#!/bin/sh

# close and remove old versions
palm-launch -c net.webpresso.froscon
palm-install -r net.webpresso.froscon

# package, install and run FrOSCon app on palm emulator
palm-package contents
palm-install net.webpresso.froscon_0.2.6_all.ipk
palm-launch net.webpresso.froscon
