#!/bin/sh

# close and remove old versions
palm-launch -c net.webpresso.fosdem
palm-install -r net.webpresso.fosdem

# package, install and run FOSDEM app on palm emulator
palm-package contents
palm-install net.webpresso.fosdem_0.2.4_all.ipk
palm-launch net.webpresso.fosdem
